services:
  - type: web
    name: pharmaflow-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false # You will need to manually add your MongoDB URI in the Render Dashboard
      - key: JWT_SECRET
        generateValue: true # Render will automatically generate a secure secret 
